In [5]:
import pandas as pd
import seaborn as sns
import os
sns.set_theme()
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
cwd = os.getcwd()
print("Current working directory:", cwd)

# Change the working directory
#os.chdir('S:/OneDrive - University of Georgia/1 UGA/1 PhD/1 Spring24/Tobacco')
#os.chdir(r'/Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/1 Spring24/Tobacco')
os.chdir(r'/Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_Chapter/madeData')


# Verify the change
print("New working directory:", os.getcwd())

Current working directory: /Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_chapter/madeData
New working directory: /Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_chapter/madeData

In [6]:
# df11 = pd.read_csv("madeData/japan_regions.csv")
df11 = pd.read_csv('/Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/1 Spring24/Tobacco/madeData/pop_income_japan.csv')

japan_pop_income_df_shape = df11.shape
# df11.info()

## Income is in million yen

In [7]:
## firstly I need to separate the spaces and the string

df11['inc_2017'] = df11['inc_2017'].str.replace(',', '').astype(int)
df11['inc_2018'] = df11['inc_2018'].str.replace(',', '').astype(int)
df11['inc_2019'] = df11['inc_2019'].str.replace(',', '').astype(int)
df11['inc_2020'] = df11['inc_2020'].str.replace(',', '').astype(int)
df11['pop_2017'] = df11['pop_2017'].str.replace(',', '').astype(int)
df11['pop_2018'] = df11['pop_2018'].str.replace(',', '').astype(int)
df11['pop_2019'] = df11['pop_2019'].str.replace(',', '').astype(int)
df11['pop_2020'] = df11['pop_2020'].str.replace(',', '').astype(int)

df11.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Prefecture  48 non-null     object
 1   region_id   48 non-null     int64
 2   inc_2017    48 non-null     int64
 3   inc_2018    48 non-null     int64
 4   inc_2019    48 non-null     int64
 5   inc_2020    48 non-null     int64
 6   pci_2017    48 non-null     object
 7   pci_2018    48 non-null     object
 8   pci_2019    48 non-null     object
 9   pci_2020    48 non-null     object
 10  pop_2017    48 non-null     int64
 11  pop_2018    48 non-null     int64
 12  pop_2019    48 non-null     int64
 13  pop_2020    48 non-null     int64
dtypes: int64(9), object(5)
memory usage: 5.4+ KB

In [8]:
df11['2017_pop'] = df11.groupby(['region_id'])['pop_2017'].transform('sum')
df11['2018_pop'] = df11.groupby(['region_id'])['pop_2018'].transform('sum')
df11['2019_pop'] = df11.groupby(['region_id'])['pop_2019'].transform('sum')
df11['2020_pop'] = df11.groupby(['region_id'])['pop_2020'].transform('sum')
df11['2017_inc'] = df11.groupby(['region_id'])['inc_2017'].transform('sum')
df11['2018_inc'] = df11.groupby(['region_id'])['inc_2018'].transform('sum')
df11['2019_inc'] = df11.groupby(['region_id'])['inc_2019'].transform('sum')
df11['2020_inc'] = df11.groupby(['region_id'])['inc_2020'].transform('sum')


df11 = df11[['region_id', '2017_pop', '2018_pop', '2019_pop', '2020_pop', '2017_inc',	'2018_inc',	'2019_inc',	'2020_inc']].copy()
df11

,region_id,2017_pop,2018_pop,2019_pop,2020_pop,2017_inc,2018_inc,2019_inc,2020_inc
0,2,5325162,5293105,5259379,5224614,14862136,14885922,15124935,14271864
1,11,8849711,8773404,8693719,8611195,25319279,25028970,24674665,23556619
2,11,8849711,8773404,8693719,8611195,25319279,25028970,24674665,23556619
3,11,8849711,8773404,8693719,8611195,25319279,25028970,24674665,23556619
4,11,8849711,8773404,8693719,8611195,25319279,25028970,24674665,23556619
5,11,8849711,8773404,8693719,8611195,25319279,25028970,24674665,23556619
6,11,8849711,8773404,8693719,8611195,25319279,25028970,24674665,23556619
7,4,7652991,7622771,7586141,7549239,25612412,25534219,24943534,23216761
8,4,7652991,7622771,7586141,7549239,25612412,25534219,24943534,23216761
9,4,7652991,7622771,7586141,7549239,25612412,25534219,24943534,23216761
10,5,36505374,36682255,36856120,36914176,151596974,153861478,150705158,141164141
11,5,36505374,36682255,36856120,36914176,151596974,153861478,150705158,141164141
12,5,36505374,36682255,36856120,36914176,151596974,153861478,150705158,141164141
13,5,36505374,36682255,36856120,36914176,151596974,153861478,150705158,141164141
14,10,4349334,4319078,4284828,4249283,12843154,12888204,12635216,11884910
15,3,2984997,2971985,2954036,2934203,9364325,9619018,9472537,8843841
16,3,2984997,2971985,2954036,2934203,9364325,9619018,9472537,8843841
17,3,2984997,2971985,2954036,2934203,9364325,9619018,9472537,8843841
18,4,7652991,7622771,7586141,7549239,25612412,25534219,24943534,23216761
19,10,4349334,4319078,4284828,4249283,12843154,12888204,12635216,11884910
20,12,15020859,15001745,14984722,14924613,53303630,53542641,51552985,48119227
21,12,15020859,15001745,14984722,14924613,53303630,53542641,51552985,48119227
22,12,15020859,15001745,14984722,14924613,53303630,53542641,51552985,48119227
23,12,15020859,15001745,14984722,14924613,53303630,53542641,51552985,48119227
24,6,20671090,20632636,20601929,20541441,62673655,62887569,62250820,58354723
25,6,20671090,20632636,20601929,20541441,62673655,62887569,62250820,58354723
26,6,20671090,20632636,20601929,20541441,62673655,62887569,62250820,58354723
27,6,20671090,20632636,20601929,20541441,62673655,62887569,62250820,58354723
28,6,20671090,20632636,20601929,20541441,62673655,62887569,62250820,58354723
29,6,20671090,20632636,20601929,20541441,62673655,62887569,62250820,58354723
30,1,7379369,7341111,7300780,7254726,22555163,21999636,21639102,20391661
31,1,7379369,7341111,7300780,7254726,22555163,21999636,21639102,20391661
32,1,7379369,7341111,7300780,7254726,22555163,21999636,21639102,20391661
33,1,7379369,7341111,7300780,7254726,22555163,21999636,21639102,20391661
34,1,7379369,7341111,7300780,7254726,22555163,21999636,21639102,20391661
35,9,3794292,3763791,3731055,3696171,10739232,10651012,10642284,9775360
36,9,3794292,3763791,3731055,3696171,10739232,10651012,10642284,9775360
37,9,3794292,3763791,3731055,3696171,10739232,10651012,10642284,9775360
38,9,3794292,3763791,3731055,3696171,10739232,10651012,10642284,9775360
39,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
40,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
41,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
42,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
43,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
44,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
45,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
46,8,1447594,1454074,1461543,1467480,3352967,3378820,3414120,3197328
47,0,126918546,126748506,126555078,126146099,427319923,429409511,421894262,395168409

In [9]:
df11 = df11.drop_duplicates()
japan_pop_income_df_dedup_shape = df11.shape
df11

,region_id,2017_pop,2018_pop,2019_pop,2020_pop,2017_inc,2018_inc,2019_inc,2020_inc
0,2,5325162,5293105,5259379,5224614,14862136,14885922,15124935,14271864
1,11,8849711,8773404,8693719,8611195,25319279,25028970,24674665,23556619
7,4,7652991,7622771,7586141,7549239,25612412,25534219,24943534,23216761
10,5,36505374,36682255,36856120,36914176,151596974,153861478,150705158,141164141
14,10,4349334,4319078,4284828,4249283,12843154,12888204,12635216,11884910
15,3,2984997,2971985,2954036,2934203,9364325,9619018,9472537,8843841
20,12,15020859,15001745,14984722,14924613,53303630,53542641,51552985,48119227
24,6,20671090,20632636,20601929,20541441,62673655,62887569,62250820,58354723
30,1,7379369,7341111,7300780,7254726,22555163,21999636,21639102,20391661
35,9,3794292,3763791,3731055,3696171,10739232,10651012,10642284,9775360
39,7,12937773,12892551,12840826,12778958,35096996,35132022,34838906,32391974
46,8,1447594,1454074,1461543,1467480,3352967,3378820,3414120,3197328
47,0,126918546,126748506,126555078,126146099,427319923,429409511,421894262,395168409

In [10]:
# lets melt the dataset to make it the long form
# df11 = df11['region_id', 'region_name', '2017_pop', '2018_pop', '2019_pop',	'2020_pop', '2017_inc',	'2018_inc',	'2019_inc',	'2020_inc'].drop_duplicates().copy()
df_long = pd.melt(df11, id_vars=['region_id'], value_vars=['2017_pop',	'2018_pop',	'2019_pop',	'2020_pop'], var_name='PopYear', value_name='PopValue')
df_long2 = pd.melt(df11, id_vars=['region_id'], value_vars=['2017_inc',	'2018_inc',	'2019_inc',	'2020_inc'], var_name='IncYear', value_name='IncValue')
# df_long['PopYear'] = 
df_concat = pd.concat([df_long, df_long2['IncValue']], axis="columns")
df_concat 

# df_long = df_long.rename(columns = {'PopYear: Year'})
# merged_df = pd.merge(df, df1, on=['region', 'year'], how='inner')

df_concat['year'] = df_concat['PopYear'].str.split('[ _]').str[0]

In [11]:
df1 = df_concat[['region_id', 'year', 'PopValue', 'IncValue']]
df1 = df1.rename(columns = {'region_id': 'region'})

In [12]:
def recode_total_as13(region):
    if region == 0:
        return 13
    return region

df1['region'] = df1.region.apply(recode_total_as13)
df1

    region  year   PopValue   IncValue
0        2  2017    5325162   14862136
1       11  2017    8849711   25319279
2        4  2017    7652991   25612412
3        5  2017   36505374  151596974
4       10  2017    4349334   12843154
5        3  2017    2984997    9364325
6       12  2017   15020859   53303630
7        6  2017   20671090   62673655
8        1  2017    7379369   22555163
9        9  2017    3794292   10739232
10       7  2017   12937773   35096996
11       8  2017    1447594    3352967
12      13  2017  126918546  427319923
13       2  2018    5293105   14885922
14      11  2018    8773404   25028970
15       4  2018    7622771   25534219
16       5  2018   36682255  153861478
17      10  2018    4319078   12888204
18       3  2018    2971985    9619018
19      12  2018   15001745   53542641
20       6  2018   20632636   62887569
21       1  2018    7341111   21999636
22       9  2018    3763791   10651012
23       7  2018   12892551   35132022
24       8  2018    1454074    3378820
25      13  2018  126748506  429409511
26       2  2019    5259379   15124935
27      11  2019    8693719   24674665
28       4  2019    7586141   24943534
29       5  2019   36856120  150705158
30      10  2019    4284828   12635216
31       3  2019    2954036    9472537
32      12  2019   14984722   51552985
33       6  2019   20601929   62250820
34       1  2019    7300780   21639102
35       9  2019    3731055   10642284
36       7  2019   12840826   34838906
37       8  2019    1461543    3414120
38      13  2019  126555078  421894262
39       2  2020    5224614   14271864
40      11  2020    8611195   23556619
41       4  2020    7549239   23216761
42       5  2020   36914176  141164141
43      10  2020    4249283   11884910
44       3  2020    2934203    8843841
45      12  2020   14924613   48119227
46       6  2020   20541441   58354723
47       1  2020    7254726   20391661
48       9  2020    3696171    9775360
49       7  2020   12778958   32391974
50       8  2020    1467480    3197328
51      13  2020  126146099  395168409

In [13]:
# Print column types of both DataFrames

print("Data types in df1:")
print(df1.dtypes)

# Convert 'year' column to integer in both DataFrames
df1['year'] = df1['year'].astype(int)

Data types in df1:
region       int64
year        object
PopValue     int64
IncValue     int64
dtype: object

In [14]:
## Saving the cleaned income dataset
df1.to_csv('INCOME_FINAL.csv', index=False) #region-year level
df1

    region  year   PopValue   IncValue
0        2  2017    5325162   14862136
1       11  2017    8849711   25319279
2        4  2017    7652991   25612412
3        5  2017   36505374  151596974
4       10  2017    4349334   12843154
5        3  2017    2984997    9364325
6       12  2017   15020859   53303630
7        6  2017   20671090   62673655
8        1  2017    7379369   22555163
9        9  2017    3794292   10739232
10       7  2017   12937773   35096996
11       8  2017    1447594    3352967
12      13  2017  126918546  427319923
13       2  2018    5293105   14885922
14      11  2018    8773404   25028970
15       4  2018    7622771   25534219
16       5  2018   36682255  153861478
17      10  2018    4319078   12888204
18       3  2018    2971985    9619018
19      12  2018   15001745   53542641
20       6  2018   20632636   62887569
21       1  2018    7341111   21999636
22       9  2018    3763791   10651012
23       7  2018   12892551   35132022
24       8  2018    1454074    3378820
25      13  2018  126748506  429409511
26       2  2019    5259379   15124935
27      11  2019    8693719   24674665
28       4  2019    7586141   24943534
29       5  2019   36856120  150705158
30      10  2019    4284828   12635216
31       3  2019    2954036    9472537
32      12  2019   14984722   51552985
33       6  2019   20601929   62250820
34       1  2019    7300780   21639102
35       9  2019    3731055   10642284
36       7  2019   12840826   34838906
37       8  2019    1461543    3414120
38      13  2019  126555078  421894262
39       2  2020    5224614   14271864
40      11  2020    8611195   23556619
41       4  2020    7549239   23216761
42       5  2020   36914176  141164141
43      10  2020    4249283   11884910
44       3  2020    2934203    8843841
45      12  2020   14924613   48119227
46       6  2020   20541441   58354723
47       1  2020    7254726   20391661
48       9  2020    3696171    9775360
49       7  2020   12778958   32391974
50       8  2020    1467480    3197328
51      13  2020  126146099  395168409