In [22]:
import pandas as pd
import seaborn as sns
import numpy as np
import statsmodels.api as sm
import os
sns.set_theme()
from sklearn.preprocessing import LabelEncoder
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
cwd = os.getcwd()
print("Current working directory:", cwd)

# Change the working directory
#os.chdir('S:/OneDrive - University of Georgia/1 UGA/1 PhD/1 Spring24/Tobacco')
#os.chdir(r'/Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/1 Spring24/Tobacco')

os.chdir(r'/Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_Chapter/madeData')

# Verify the change
print("New working directory:", os.getcwd())

Current working directory: /Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_chapter/madeData
New working directory: /Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_chapter/madeData

In [23]:
df1 = pd.read_csv('heat_smoke_market_FINAL.csv')
df2 = pd.read_csv('INCOME_FINAL.csv')
df3 = pd.read_csv('price_indices_FINAL.csv')
df4 = pd.read_csv('other_var_FINAL.csv')

Lets MERGEEEE

In [24]:
## merging these two datasets on W and region variables:
merged_df1 = pd.merge(df1, df3, on=['W', 'region'], how='inner')
merged_df2 = pd.merge(merged_df1, df4, on=['W', 'region'], how='inner')
merged_FINAL = pd.merge(merged_df2, df2, on=['region', 'year'], how='inner')

In [25]:
merged_FINAL

,W,region,year,totrev_Smoke,qt_Smoke,totrev_Heat,qt_Heat,Laspeyres_Smoke,Paasche_Smoke,Fisher_Smoke,...,Laspeyres_Heat,Paasche_Heat,Fisher_Heat,Tornqvist_Heat,CPI,ln_CPI,weekly_percap_income,weekly_percap_exp,PopValue,IncValue
0,1,1,2017,2.574840e+06,5578.204,209494.044,414.742,0.960471,0.960322,0.960397,...,0.953496,0.953712,0.953604,0.976514,98.50,4.590057,23411.669105,15623.322767,7379369,22555163
1,1,2,2017,2.729862e+06,5567.702,150458.728,296.045,0.960350,0.960085,0.960218,...,0.953464,0.953793,0.953629,0.976555,97.50,4.579852,32965.644967,14137.930349,5325162,14862136
2,1,3,2017,1.046158e+06,2116.976,57934.923,112.455,0.960401,0.961194,0.960797,...,0.953484,0.953834,0.953659,0.976576,98.30,4.588024,22657.237490,17272.969612,2984997,9364325
3,1,4,2017,3.198163e+06,7037.711,213254.932,439.983,0.960328,0.960726,0.960527,...,0.953479,0.953793,0.953636,0.976555,98.00,4.584967,28318.976409,25697.525364,7652991,25612412
4,1,5,2017,1.337419e+07,29068.790,1035634.873,2102.634,0.960375,0.960989,0.960682,...,0.953481,0.953857,0.953669,0.976588,97.85,4.583436,25039.147976,20719.002146,36505374,151596974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2191,183,8,2020,4.984312e+05,1075.484,164780.339,336.905,1.042209,1.042764,1.042487,...,1.044072,1.029621,1.036822,1.015022,100.00,4.605170,43651.112290,33415.131712,1467480,3197328
2192,183,9,2020,1.348564e+06,2465.845,371034.720,680.921,1.042580,1.041026,1.041803,...,1.044160,1.029139,1.036622,1.014790,100.10,4.606170,87753.555561,40521.702895,3696171,9775360
2193,183,10,2020,1.347240e+06,2565.614,503146.661,950.301,1.042691,1.038873,1.040781,...,1.044087,1.027788,1.035905,1.014124,100.10,4.606170,74497.230566,50971.621417,4249283,11884910
2194,183,11,2020,3.096018e+06,6137.084,1330899.271,2506.863,1.042050,1.038753,1.040400,...,1.043995,1.026790,1.035357,1.013632,99.85,4.603669,64612.736910,35669.292833,8611195,23556619
2195,183,12,2020,4.644789e+06,8551.305,2057522.963,3654.706,1.042086,1.039866,1.040975,...,1.043923,1.026924,1.035389,1.013695,100.00,4.605170,113872.374167,60306.605335,14924613,48119227

In [26]:
# processing merged final into removing the national region

merged_FINAL = merged_FINAL[merged_FINAL['region']!=13]
merged_FINAL

,W,region,year,totrev_Smoke,qt_Smoke,totrev_Heat,qt_Heat,Laspeyres_Smoke,Paasche_Smoke,Fisher_Smoke,...,Laspeyres_Heat,Paasche_Heat,Fisher_Heat,Tornqvist_Heat,CPI,ln_CPI,weekly_percap_income,weekly_percap_exp,PopValue,IncValue
0,1,1,2017,2.574840e+06,5578.204,209494.044,414.742,0.960471,0.960322,0.960397,...,0.953496,0.953712,0.953604,0.976514,98.50,4.590057,23411.669105,15623.322767,7379369,22555163
1,1,2,2017,2.729862e+06,5567.702,150458.728,296.045,0.960350,0.960085,0.960218,...,0.953464,0.953793,0.953629,0.976555,97.50,4.579852,32965.644967,14137.930349,5325162,14862136
2,1,3,2017,1.046158e+06,2116.976,57934.923,112.455,0.960401,0.961194,0.960797,...,0.953484,0.953834,0.953659,0.976576,98.30,4.588024,22657.237490,17272.969612,2984997,9364325
3,1,4,2017,3.198163e+06,7037.711,213254.932,439.983,0.960328,0.960726,0.960527,...,0.953479,0.953793,0.953636,0.976555,98.00,4.584967,28318.976409,25697.525364,7652991,25612412
4,1,5,2017,1.337419e+07,29068.790,1035634.873,2102.634,0.960375,0.960989,0.960682,...,0.953481,0.953857,0.953669,0.976588,97.85,4.583436,25039.147976,20719.002146,36505374,151596974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2191,183,8,2020,4.984312e+05,1075.484,164780.339,336.905,1.042209,1.042764,1.042487,...,1.044072,1.029621,1.036822,1.015022,100.00,4.605170,43651.112290,33415.131712,1467480,3197328
2192,183,9,2020,1.348564e+06,2465.845,371034.720,680.921,1.042580,1.041026,1.041803,...,1.044160,1.029139,1.036622,1.014790,100.10,4.606170,87753.555561,40521.702895,3696171,9775360
2193,183,10,2020,1.347240e+06,2565.614,503146.661,950.301,1.042691,1.038873,1.040781,...,1.044087,1.027788,1.035905,1.014124,100.10,4.606170,74497.230566,50971.621417,4249283,11884910
2194,183,11,2020,3.096018e+06,6137.084,1330899.271,2506.863,1.042050,1.038753,1.040400,...,1.043995,1.026790,1.035357,1.013632,99.85,4.603669,64612.736910,35669.292833,8611195,23556619
2195,183,12,2020,4.644789e+06,8551.305,2057522.963,3654.706,1.042086,1.039866,1.040975,...,1.043923,1.026924,1.035389,1.013695,100.00,4.605170,113872.374167,60306.605335,14924613,48119227

In [27]:
merged_FINAL.to_csv('FINAL_Chapter1.csv', index=False)